name: Unity WebGL Local Build

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    name: Build WebGL (Local)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Unity - Builder
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.37f1
          targetPlatform: WebGL
          buildMethod: BuildScript.BuildWebGLLocal

      - name: Upload WebGL Build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Local-Build
          path: Builds/Local/webgl_1.1
