name: Unity WebGL BR Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-webgl:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run Unity WebGL Brotli Build
      - name: Build WebGL (Brotli)
        run: >
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe"
          -quit -batchmode -nographics
          -projectPath "$env:GITHUB_WORKSPACE"
          -executeMethod BuildScript.BuildWebGLBR
          -logFile "$env:GITHUB_WORKSPACE\build.log"

      # Step 3: Show build folder for debugging
      - name: Debug: Show Build Output
        run: |
          echo "=== Root Directory ==="
          dir "$env:GITHUB_WORKSPACE"
          echo "=== Build Directory ==="
          dir "$env:GITHUB_WORKSPACE\Builds\BR"

      # Step 4: Zip the Brotli Build
      - name: Zip WebGL Build
        run: >
          Compress-Archive -Path "$env:GITHUB_WORKSPACE\Builds\BR\*" 
          -DestinationPath "$env:GITHUB_WORKSPACE\WebGLBuild.zip" -Force

      # Step 5: Verify Zip Exists
      - name: Debug: Confirm Zip Exists
        run: |
          if (Test-Path "$env:GITHUB_WORKSPACE\WebGLBuild.zip") {
            echo "ZIP created successfully"
          } else {
            echo "ERROR: ZIP not created!"
            exit 1
          }

      # Step 6: Upload Artifact
      - name: Upload WebGL Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild-Brotli
          path: WebGLBuild.zip
