name: Unity WebGL Build (Local)

on:
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  build-webgl-local:
    runs-on: self-hosted

    steps:
      # 1. (Optional) Checkout repository if needed for scripts/assets
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      # 2. Run Unity to build WebGL (Local)
      - name: Build WebGL (Local)
        run: |
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" -quit -batchmode -nographics  -projectPath "C:\Unityprojects\abs-unity" -executeMethod BuildScript.BuildWebGLLocal -logFile "C:\Unityprojects\abs-unity\build.log"
   
        shell: powershell

      # 3. Upload the WebGL build folder as an artifact
      - name: Upload WebGL Local Build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL_Local_Build
          path: "C:/Unityprojects/abs-unity/Builds/Local/webgl_1.1"

