name: Unity WebGL Local Build

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-webgl:
    runs-on: self-hosted

    steps:
      # 1. Check runner connectivity and log Unity version
      - name: Verify Unity Installation
        run: |
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" -version
        shell: powershell

      # 2. Run Unity to create a Local WebGL build
      - name: Build WebGL (Local)
        run: |
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" `
            -quit `
            -batchmode `
            -nographics `
            -projectPath "C:\Unityprojects\abs-unity" `
            -executeMethod BuildScript.BuildWebGLLocal `
            -logFile "C:\Unityprojects\abs-unity\build.log"
        shell: powershell

      # 3. Upload the generated WebGL build as an artifact
      - name: Upload WebGL Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGL_Local_Build
          path: C:/Unityprojects/abs-unity/Builds/Local/webgl_1.1
