name: Test Manual Workflow

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Test Step
        run: echo "Manual workflow is working!"
