name: Build Unity Local WebGL

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-webgl-local:
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      # 1. Checkout repository without cleaning Library
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      # 2. Verify Unity installation
      - name: Check Unity Version
        shell: powershell
        run: |
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" --version

      # 3. Run Unity Local WebGL build
      - name: Build Local WebGL
        shell: powershell
        run: |
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" `
            -quit -batchmode -nographics `
            -projectPath "$env:GITHUB_WORKSPACE\Prudent-Unity" `
            -executeMethod BuildScript.BuildWebGLLocal `
            -logFile "$env:GITHUB_WORKSPACE\Prudent-Unity\build.log"

      # 4. Verify that the build succeeded
      - name: Verify Local WebGL Build
        shell: powershell
        run: |
          $buildPath = "$env:GITHUB_WORKSPACE\Prudent-Unity\Builds\Local\webgl_1.1\index.html"
          if (!(Test-Path $buildPath)) {
            Write-Host "ERROR: Unity did not produce a Local WebGL build!"
            Get-Content "$env:GITHUB_WORKSPACE\Prudent-Unity\build.log"
            exit 1
          } else {
            Write-Host "Local WebGL build verified successfully."
          }

      # 5. Upload artifact for download (optional)
      - name: Upload Local WebGL Build
        uses: actions/upload-artifact@v4
        with:
          name: LocalWebGLBuild
          path: Prudent-Unity/Builds/Local/webgl_1.1
