name: Unity WebGL Brotli Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-webgl:
    runs-on: [self-hosted, Windows, X64]  # or use custom label if you added one

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run Unity WebGL Brotli Build
      - name: Build WebGL (Brotli)
        run: >
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe"
          -quit -batchmode -nographics
          -projectPath "$env:GITHUB_WORKSPACE"
          -executeMethod BuildScript.BuildWebGLBR
          -logFile "$env:GITHUB_WORKSPACE\build.log"

      # Step 3: Verify Brotli Build
      - name: Verify Brotli Build
        run: |
          if (!(Test-Path "$env:GITHUB_WORKSPACE\Builds\BR\webgl_1.1\index.html")) {
            echo "ERROR: Unity did not produce a new Brotli build!"
            Get-Content "$env:GITHUB_WORKSPACE\build.log"
            exit 1
          } else {
            echo "Brotli build verified successfully."
          }

      # Step 4: Zip the Build
      - name: Zip WebGL BR Build
        run: >
          Compress-Archive -Path "$env:GITHUB_WORKSPACE\Builds\BR\*"
          -DestinationPath "$env:GITHUB_WORKSPACE\WebGLBuild.zip" -Force

      # Step 5: Upload as Artifact
      - name: Upload WebGL Build Zip
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild-Brotli
          path: WebGLBuild.zip
