name: Unity WebGL Local Build

on:
  workflow_dispatch: # Enables the manual run button in GitHub

jobs:
  build-webgl:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false # Keeps Library folder if exists for faster builds

      - name: Check Unity Version
        shell: pwsh
        run: |
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" --version

      - name: Build Unity Project (Local WebGL)
        shell: pwsh
        run: |
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" `
            -quit `
            -batchmode `
            -nographics `
            -projectPath "$env:GITHUB_WORKSPACE\Prudent-Unity\Prudent-Unity" `
            -executeMethod BuildScript.BuildWebGLLocal `
            -logFile "$env:GITHUB_WORKSPACE\Prudent-Unity\Prudent-Unity\build.log"

      - name: Verify WebGL Build
        shell: pwsh
        run: |
          $buildPath = "$env:GITHUB_WORKSPACE\Prudent-Unity\Prudent-Unity\Builds\Local\webgl_1.1\index.html"
          if (!(Test-Path $buildPath)) {
            Write-Host "ERROR: Unity did not produce a Local WebGL build!"
            Get-Content "$env:GITHUB_WORKSPACE\Prudent-Unity\Prudent-Unity\build.log"
            exit 1
          } else {
            Write-Host "Local WebGL build verified successfully."
          }

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Local-Build
          path: Prudent-Unity/Prudent-Unity/Builds/Local
