name: Build WebGL Brotli

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: false  # Keep Library folder

      - name: Build Unity WebGL (Brotli)
        shell: powershell
        run: |
          "Starting Unity build..."
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" `
            -quit -batchmode -nographics `
            -projectPath "$env:GITHUB_WORKSPACE\Prudent-Unity" `
            -executeMethod BuildScript.BuildWebGLBR `
            -logFile "$env:GITHUB_WORKSPACE\Prudent-Unity\build.log"

      - name: Verify Brotli Build
        shell: powershell
        run: |
          $buildPath = "$env:GITHUB_WORKSPACE\Prudent-Unity\Builds\BR\webgl_1.1\index.html"
          if (!(Test-Path $buildPath)) {
            Write-Host "ERROR: Unity did not produce a Brotli build!"
            Get-Content "$env:GITHUB_WORKSPACE\Prudent-Unity\build.log"
            exit 1
          } else {
            Write-Host "Brotli build verified successfully."
          }

