name: Unity WebGL Brotli Build

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-webgl:
    runs-on: self-hosted

    steps:
      # 1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Clean Unity cache (fresh build)
      - name: Clean Unity Cache
        run: |
          Remove-Item -Recurse -Force "Library" -ErrorAction Ignore
          Remove-Item -Recurse -Force "Temp" -ErrorAction Ignore
          Remove-Item -Recurse -Force "Builds\BR\webgl_1.1" -ErrorAction Ignore
        working-directory: ${{ github.workspace }}

      # 3. Run Unity Build (Brotli Production)
      - name: Build WebGL (Brotli)
        run: >
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe"
          -quit -batchmode -nographics
          -projectPath "${{ github.workspace }}"
          -executeMethod BuildScript.BuildWebGLBR
          -logFile "${{ github.workspace }}\build.log"

      # 4. Verify Build
      - name: Verify Brotli Build
        run: |
          if (!(Test-Path "${{ github.workspace }}\Builds\BR\webgl_1.1\index.html")) {
            echo "ERROR: Unity did not produce a new Brotli build!"
            Get-Content "${{ github.workspace }}\build.log"
            exit 1
          } else {
            echo "Brotli build verified successfully."
          }

      # 5. Zip and Upload Artifact
      - name: Zip WebGL BR Build
        run: |
          Compress-Archive -Path "Builds\BR\webgl_1.1\*" `
          -DestinationPath "WebGLBuild.zip" -Force

      - name: Upload WebGL Build Zip
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild-Brotli
          path: WebGLBuild.zip
