name: Unity WebGL Local Build

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  build-webgl:
    runs-on: self-hosted
    timeout-minutes: 90

    steps:
      # 1. Checkout repository without cleaning Library folder
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      # 2. Verify Unity installation path (optional)
      - name: Check Unity Version
        run: '"C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" -version'

      # 3. Run Unity build for Local (Gzip)
      - name: Build WebGL (Local Gzip)
        shell: pwsh
        run: |
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe" `
            -quit -batchmode -nographics `
            -projectPath "$env:GITHUB_WORKSPACE\Prudent-Unity" `
            -executeMethod BuildScript.BuildWebGLLocal `
            -logFile "$env:GITHUB_WORKSPACE\Prudent-Unity\build.log"

      # 4. Verify build output exists
      - name: Verify WebGL build output
        shell: pwsh
        run: |
          $buildPath = "$env:GITHUB_WORKSPACE\Prudent-Unity\Builds\LocalWebGL\webgl_local\index.html"
          if (!(Test-Path $buildPath)) {
            Write-Host "ERROR: Unity did not produce a WebGL Local build!"
            Get-Content "$env:GITHUB_WORKSPACE\Prudent-Unity\build.log"
            exit 1
          } else {
            Write-Host "Local WebGL build verified successfully."
          }

      # 5. Upload build artifact
      - name: Upload WebGL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webgl-local-build
          path: Prudent-Unity/Builds/LocalWebGL/webgl_local
