name: Unity WebGL Build (Brotli)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-webgl:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build WebGL (Brotli)
        run: >
          & "C:\Program Files\Unity\Hub\Editor\6000.0.37f1\Editor\Unity.exe"
          -quit -batchmode -nographics
          -projectPath "C:\Unityprojects\abs-unity"
          -executeMethod BuildScript.BuildWebGLBR
          -logFile "C:\Unityprojects\abs-unity\build.log"

      - name: Debug: Show Build Output
        run: |
          echo "=== Root Directory ==="
          dir "C:\Unityprojects\abs-unity"
          echo "=== Build Directory ==="
          dir "C:\Unityprojects\abs-unity\Builds\BR"

      - name: Zip WebGL BR Build
        run: >
          Compress-Archive -Path "C:\Unityprojects\abs-unity\Builds\BR\*" 
          -DestinationPath "C:\Unityprojects\abs-unity\WebGLBuild.zip" -Force

      - name: Debug: Confirm Zip Exists
        run: |
          if (Test-Path "C:\Unityprojects\abs-unity\WebGLBuild.zip") {
            echo "ZIP created successfully"
          } else {
            echo "ERROR: ZIP not created!"
            exit 1
          }

      - name: Upload WebGL Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild-Brotli
          path: "C:\\Unityprojects\\abs-unity\\WebGLBuild.zip"
